services:
  clamav-server:
    image: ajilaag/clamav-rest:latest
    ports:
      - "9443:9443"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider https://localhost:9443/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 60s
    environment:
      - MAX_FILE_SIZE=30M
